package com.banya.datagen;

import com.banya.Banya;
import com.banya.registry.ModBlocks;
import com.banya.registry.ModItems;
import net.minecraft.data.PackOutput;
import net.neoforged.neoforge.common.data.LanguageProvider;

/** Generates en_us and ru_ru lang files (one instance per locale). */
public class ModLanguageProvider extends LanguageProvider {
    private final String locale;

    public ModLanguageProvider(PackOutput output, String locale) {
        super(output, Banya.MODID, locale);
        this.locale = locale;
    }

    @Override
    protected void addTranslations() {
        if (locale.equals("ru_ru")) {
            add("itemGroup.banya", "Баня");
            add(ModBlocks.STOVE.get(), "Печь-каменка");
            add(ModBlocks.THERMOMETER.get(), "Термометр");
            add(ModItems.FELT_HAT.get(), "Банная шапка");
            add(ModItems.LADLE.get(), "Ковш");
            add(ModBlocks.TUB.get(), "Ушат");
            add(ModBlocks.POLOK.get(), "Полок");
            add(ModBlocks.BANYA_DOOR.get(), "Банная дверь");
            add(ModBlocks.SOAPSTONE_ORE.get(), "Талькохлоритовая руда");
            add(ModBlocks.SOOTY_PLANKS.get(), "Закопчённые доски");
            add(ModBlocks.SOOTY_LOG.get(), "Закопчённое бревно");
            add(ModBlocks.STOVE_CASING.get(), "Печная кладка");
            add(ModBlocks.CHIMNEY.get(), "Дымоход");
            add(ModBlocks.DAMPER.get(), "Заслонка");
            add(ModItems.RIVER_STONE.get(), "Речные голыши");
            add(ModItems.ANDESITE_STONE.get(), "Андезитовые камни");
            add(ModItems.BASALT_STONE.get(), "Базальтовые камни");
            add(ModItems.SOAPSTONE.get(), "Талькохлорит");
            add("message.banya.stone.cracked", "Камень треснул");
            add("message.banya.stone.too_hot", "Камень раскалён — его не удержать");
            add("gui.banya.stove.fire", "Печь %s °C");
            add("gui.banya.stove.stones", "Камни %s °C");
            add("tooltip.banya.stone_heat.warm", "Тёплый (%s °C)");
            add("tooltip.banya.stone_heat.hot", "Горячий (%s °C)");
            add("tooltip.banya.stone_heat.very_hot", "Очень горячий (%s °C)");
            add("tooltip.banya.stone_heat.faint_red", "Раскалённый (%s °C)");
            add("tooltip.banya.stone_heat.red", "Добела (%s °C)");
            add(ModBlocks.CHOPPING_BLOCK.get(), "Колода для колки");
            add(ModBlocks.DRYING_RACK.get(), "Дровница");
            add(ModItems.FIREWOOD_BIRCH.get(), "Берёзовые поленья");
            add(ModItems.FIREWOOD_OAK.get(), "Дубовые поленья");
            add(ModItems.FIREWOOD_SPRUCE.get(), "Еловые поленья");
            add("item.banya.firewood_birch.wet", "Сырые берёзовые поленья");
            add("item.banya.firewood_birch.dry", "Сухие берёзовые поленья");
            add("item.banya.firewood_oak.wet", "Сырые дубовые поленья");
            add("item.banya.firewood_oak.dry", "Сухие дубовые поленья");
            add("item.banya.firewood_spruce.wet", "Сырые еловые поленья");
            add("item.banya.firewood_spruce.dry", "Сухие еловые поленья");
            add("message.banya.faint", "В глазах потемнело…");
            add(ModItems.VENIK_BIRCH.get(), "Берёзовый веник");
            add(ModItems.VENIK_OAK.get(), "Дубовый веник");
            add("item.banya.venik_birch.steeped", "Запаренный берёзовый веник");
            add("item.banya.venik_oak.steeped", "Запаренный дубовый веник");
            add("message.banya.tub.cold", "Вода в ушате ещё холодная — протопи баню");
            add("message.banya.venik.dry", "Сухой веник крошится — запарь его в ушате");
            add("message.banya.venik.too_cold", "Париться можно только в жаркой парной");
            add("message.banya.venik.received", "%s парит вас веником");
            add("message.banya.venik.dried_out", "Веник высох — запарь его снова");
            add("effect.banya.hardening", "Закалка");
            add("message.banya.hardening", "Закалка!");
            add("container.banya.stove.t1", "Печь-каменка");
            add("container.banya.stove.t2", "Кирпичная каменка");
            add("container.banya.stove.t3", "Массивная печь");
            add("effect.banya.smoke_poisoning", "Угар");
            add("death.attack.banya.smoke_poisoning", "%1$s угорел в бане");
            add("container.banya.thermometer", "Термометр");
            add("gui.banya.thermometer.temperature", "Температура");
            add("gui.banya.thermometer.humidity", "Влажность");
            add("gui.banya.thermometer.heat_index", "Ощущается как");
            add("gui.banya.thermometer.smoke", "Задымлённость");
            add("gui.banya.thermometer.degrees", "%s °C");
            add("gui.banya.thermometer.percent", "%s%%");
            add("gui.banya.thermometer.sealed", "Парная замкнута");
            add("gui.banya.thermometer.leaking", "Парная не замкнута");
            add("gui.banya.thermometer.room", "Объём %s, стены %s");
            add("message.banya.thermometer.no_stove", "Печь не найдена");
            add("message.banya.overheat", "Голова кружится — пора выйти");
            add("message.banya.steam.heavy", "Тяжёлый пар — камни ещё не раскалились");
            add("entity.banya.seat", "Сиденье");
            add("subtitles.banya.steam_hiss", "Вода шипит на камнях");
            add("subtitles.banya.stone_crack", "Камень трескается");
            add("subtitles.banya.stove_crackle", "Печь потрескивает");
            add("subtitles.banya.damper_open", "Заслонка открывается");
            add("subtitles.banya.damper_close", "Заслонка закрывается");
            add("subtitles.banya.venik_whisk", "Свист веника");
            add("subtitles.banya.venik_steep", "Веник запаривается");
            add("subtitles.banya.tub_fill", "Ушат наполняется");
            add("subtitles.banya.ladle_fill", "Ковш зачерпывает");
            add("subtitles.banya.stone_scald", "Камень обжигает");
            add("subtitles.banya.stone_quench", "Камень остывает в воде");
            add("subtitles.banya.hardening", "Обжигающий холод");
            add("subtitles.banya.felt_hat_equip", "Шапка надета");
            add("subtitles.banya.chop", "Полено раскалывается");
            add("subtitles.banya.wood_load", "Дрова укладываются");
            add("advancements.banya.root.title", "Первый пар");
            add("advancements.banya.root.description", "Протопить баню и прогреться в ней");
            add("advancements.banya.light_steam.title", "С лёгким паром!");
            add("advancements.banya.light_steam.description", "Попариться веником, как положено");
            add("advancements.banya.black_banya.title", "Баня по-чёрному");
            add("advancements.banya.black_banya.description",
                    "Париться там, где копоть на стенах делает пар мягче");
            add("advancements.banya.walrus.title", "Морж");
            add("advancements.banya.walrus.description", "Три захода из парной в холодную воду подряд");
            add("advancements.banya.choked.title", "Угорел…");
            add("advancements.banya.choked.description", "Остаться в дыму до потери сознания");
        } else {
            add("itemGroup.banya", "Banya");
            add(ModBlocks.STOVE.get(), "Banya Stove");
            add(ModBlocks.THERMOMETER.get(), "Thermometer");
            add(ModItems.FELT_HAT.get(), "Felt Banya Hat");
            add(ModItems.LADLE.get(), "Ladle");
            add(ModBlocks.TUB.get(), "Banya Tub");
            add(ModBlocks.POLOK.get(), "Polok Bench");
            add(ModBlocks.BANYA_DOOR.get(), "Banya Door");
            add(ModBlocks.SOAPSTONE_ORE.get(), "Soapstone Ore");
            add(ModBlocks.SOOTY_PLANKS.get(), "Sooty Planks");
            add(ModBlocks.SOOTY_LOG.get(), "Sooty Log");
            add(ModBlocks.STOVE_CASING.get(), "Stove Casing");
            add(ModBlocks.CHIMNEY.get(), "Chimney");
            add(ModBlocks.DAMPER.get(), "Damper");
            add(ModItems.RIVER_STONE.get(), "River Stones");
            add(ModItems.ANDESITE_STONE.get(), "Andesite Stones");
            add(ModItems.BASALT_STONE.get(), "Basalt Stones");
            add(ModItems.SOAPSTONE.get(), "Soapstone");
            add("message.banya.stone.cracked", "A stone cracked");
            add("message.banya.stone.too_hot", "The stone is scalding — you cannot hold it");
            add("gui.banya.stove.fire", "Fire %s °C");
            add("gui.banya.stove.stones", "Stones %s °C");
            add("tooltip.banya.stone_heat.warm", "Warm (%s °C)");
            add("tooltip.banya.stone_heat.hot", "Hot (%s °C)");
            add("tooltip.banya.stone_heat.very_hot", "Very hot (%s °C)");
            add("tooltip.banya.stone_heat.faint_red", "Faint red (%s °C)");
            add("tooltip.banya.stone_heat.red", "Glowing red (%s °C)");
            add(ModBlocks.CHOPPING_BLOCK.get(), "Chopping Block");
            add(ModBlocks.DRYING_RACK.get(), "Drying Rack");
            add(ModItems.FIREWOOD_BIRCH.get(), "Birch Firewood");
            add(ModItems.FIREWOOD_OAK.get(), "Oak Firewood");
            add(ModItems.FIREWOOD_SPRUCE.get(), "Spruce Firewood");
            add("item.banya.firewood_birch.wet", "Damp Birch Firewood");
            add("item.banya.firewood_birch.dry", "Dry Birch Firewood");
            add("item.banya.firewood_oak.wet", "Damp Oak Firewood");
            add("item.banya.firewood_oak.dry", "Dry Oak Firewood");
            add("item.banya.firewood_spruce.wet", "Damp Spruce Firewood");
            add("item.banya.firewood_spruce.dry", "Dry Spruce Firewood");
            add("message.banya.faint", "Everything goes dark…");
            add(ModItems.VENIK_BIRCH.get(), "Birch Venik");
            add(ModItems.VENIK_OAK.get(), "Oak Venik");
            add("item.banya.venik_birch.steeped", "Steeped Birch Venik");
            add("item.banya.venik_oak.steeped", "Steeped Oak Venik");
            add("message.banya.tub.cold", "The tub water is still cold — heat the banya first");
            add("message.banya.venik.dry", "A dry venik just crumbles — steep it in a tub");
            add("message.banya.venik.too_cold", "You can only whisk in a hot parnaya");
            add("message.banya.venik.received", "%s is whisking you with a venik");
            add("message.banya.venik.dried_out", "The venik has dried out — steep it again");
            add("effect.banya.hardening", "Hardening");
            add("message.banya.hardening", "Hardening!");
            add("container.banya.stove.t1", "Banya Stove");
            add("container.banya.stove.t2", "Brick Kamenka");
            add("container.banya.stove.t3", "Massive Stove");
            add("effect.banya.smoke_poisoning", "Smoke Poisoning");
            add("death.attack.banya.smoke_poisoning", "%1$s suffocated in the banya's smoke");
            add("container.banya.thermometer", "Thermometer");
            add("gui.banya.thermometer.temperature", "Temperature");
            add("gui.banya.thermometer.humidity", "Humidity");
            add("gui.banya.thermometer.heat_index", "Feels like");
            add("gui.banya.thermometer.smoke", "Smoke");
            add("gui.banya.thermometer.degrees", "%s °C");
            add("gui.banya.thermometer.percent", "%s%%");
            add("gui.banya.thermometer.sealed", "Room is sealed");
            add("gui.banya.thermometer.leaking", "Room is not sealed");
            add("gui.banya.thermometer.room", "Volume %s, walls %s");
            add("message.banya.thermometer.no_stove", "No stove nearby");
            add("message.banya.overheat", "Your head is swimming — time to step out");
            add("message.banya.steam.heavy", "Heavy steam — the stones are not hot enough yet");
            add("entity.banya.seat", "Seat");
            add("subtitles.banya.steam_hiss", "Water hisses on stones");
            add("subtitles.banya.stone_crack", "Stone cracks");
            add("subtitles.banya.stove_crackle", "Stove crackles");
            add("subtitles.banya.damper_open", "Damper opens");
            add("subtitles.banya.damper_close", "Damper closes");
            add("subtitles.banya.venik_whisk", "Venik swishes");
            add("subtitles.banya.venik_steep", "Venik steeps");
            add("subtitles.banya.tub_fill", "Tub fills");
            add("subtitles.banya.ladle_fill", "Ladle scoops");
            add("subtitles.banya.stone_scald", "Stone scalds");
            add("subtitles.banya.stone_quench", "Stone quenches");
            add("subtitles.banya.hardening", "Biting cold");
            add("subtitles.banya.felt_hat_equip", "Hat put on");
            add("subtitles.banya.chop", "Log splits");
            add("subtitles.banya.wood_load", "Firewood stacked");
            add("advancements.banya.root.title", "First Steam");
            add("advancements.banya.root.description", "Fire the banya up and warm through in it");
            add("advancements.banya.light_steam.title", "S lyogkim parom!");
            add("advancements.banya.light_steam.description", "Take a proper venik round");
            add("advancements.banya.black_banya.title", "Banya po-chornomu");
            add("advancements.banya.black_banya.description",
                    "Steam where the soot on the walls makes the steam softer");
            add("advancements.banya.walrus.title", "Walrus");
            add("advancements.banya.walrus.description", "Three runs from the heat into cold water");
            add("advancements.banya.choked.title", "Ugorel...");
            add("advancements.banya.choked.description", "Stay in the smoke until you pass out");
        }
    }
}
