package com.impossibles5.heatandsteam.datagen;

import com.impossibles5.heatandsteam.HeatAndSteam;
import com.impossibles5.heatandsteam.registry.ModBlocks;
import com.impossibles5.heatandsteam.registry.ModItems;
import net.minecraft.data.PackOutput;
import net.neoforged.neoforge.common.data.LanguageProvider;

public class ModLanguageProvider extends LanguageProvider {
    private final String locale;

    public ModLanguageProvider(PackOutput output, String locale) {
        super(output, HeatAndSteam.MODID, locale);
        this.locale = locale;
    }

    @Override
    protected void addTranslations() {
        if (locale.equals("ru_ru")) {
            add("itemGroup.heat_and_steam", "Жар и пар");
            add(ModBlocks.STOVE.get(), "Печь-каменка");
            add(ModBlocks.THERMOMETER.get(), "Термометр");
            add(ModItems.FELT_HAT.get(), "Банная шапка");
            add(ModItems.LADLE.get(), "Ковш");
            add(ModBlocks.TUB.get(), "Ушат");
            add(ModBlocks.SAUNA_BENCH.get(), "Полок");
            add(ModBlocks.SAUNA_DOOR.get(), "Банная дверь");
            add(ModBlocks.TALCOCHLORITE_ORE.get(), "Талькохлоритовая руда");
            add(ModBlocks.SOOTY_PLANKS.get(), "Закопчённые доски");
            add(ModBlocks.SOOTY_LOG.get(), "Закопчённое бревно");
            add(ModBlocks.STOVE_CASING.get(), "Печная кладка");
            add(ModBlocks.CHIMNEY.get(), "Дымоход");
            add(ModBlocks.DAMPER.get(), "Заслонка");
            add(ModItems.RIVER_STONE.get(), "Речной камень");
            add(ModItems.ANDESITE_STONE.get(), "Андезитовый камень");
            add(ModItems.BASALT_STONE.get(), "Базальтовый камень");
            add(ModItems.TALCOCHLORITE_STONE.get(), "Талькохлоритовый камень");
            add("message.heat_and_steam.stone.cracked", "Камень треснул");
            add("message.heat_and_steam.stone.too_hot", "Камень раскалён, его не удержать");
            add("gui.heat_and_steam.stove.fire", "Печь %s °C");
            add("gui.heat_and_steam.stove.stones", "Камни %s °C");
            add("tooltip.heat_and_steam.stone_heat.warm", "Тёплый (%s °C)");
            add("tooltip.heat_and_steam.stone_heat.hot", "Горячий (%s °C)");
            add("tooltip.heat_and_steam.stone_heat.very_hot", "Очень горячий (%s °C)");
            add("tooltip.heat_and_steam.stone_heat.faint_red", "Раскалённый (%s °C)");
            add("tooltip.heat_and_steam.stone_heat.red", "Добела (%s °C)");
            add(ModBlocks.CHOPPING_BLOCK.get(), "Колода для колки");
            add(ModBlocks.DRYING_RACK.get(), "Дровница");
            add(ModItems.FIREWOOD_BIRCH.get(), "Берёзовые поленья");
            add(ModItems.FIREWOOD_OAK.get(), "Дубовые поленья");
            add(ModItems.FIREWOOD_SPRUCE.get(), "Еловые поленья");
            add("item.heat_and_steam.firewood_birch.wet", "Сырые берёзовые поленья");
            add("item.heat_and_steam.firewood_birch.dry", "Сухие берёзовые поленья");
            add("item.heat_and_steam.firewood_oak.wet", "Сырые дубовые поленья");
            add("item.heat_and_steam.firewood_oak.dry", "Сухие дубовые поленья");
            add("item.heat_and_steam.firewood_spruce.wet", "Сырые еловые поленья");
            add("item.heat_and_steam.firewood_spruce.dry", "Сухие еловые поленья");
            add("message.heat_and_steam.faint", "В глазах потемнело…");
            add(ModItems.WHISK_BIRCH.get(), "Берёзовый веник");
            add(ModItems.WHISK_OAK.get(), "Дубовый веник");
            add("item.heat_and_steam.whisk_birch.soaked", "Запаренный берёзовый веник");
            add("item.heat_and_steam.whisk_oak.soaked", "Запаренный дубовый веник");
            add("message.heat_and_steam.tub.cold", "Вода в ушате ещё холодная. Протопи баню");
            add("message.heat_and_steam.whisk.dry", "Сухой веник крошится. Запарь его в ушате");
            add("message.heat_and_steam.whisk.too_cold", "Париться можно только в жаркой парной");
            add("message.heat_and_steam.whisk.received", "%s парит вас веником");
            add("message.heat_and_steam.whisk.dried_out", "Веник высох. Запарь его снова");
            add("effect.heat_and_steam.hardening", "Закалка");
            add("message.heat_and_steam.hardening", "Закалка!");
            add("container.heat_and_steam.stove.t1", "Печь-каменка");
            add("container.heat_and_steam.stove.t2", "Кирпичная каменка");
            add("container.heat_and_steam.stove.t3", "Массивная печь");
            add("effect.heat_and_steam.smoke_poisoning", "Угар");
            add("death.attack.heat_and_steam.smoke_poisoning", "%1$s угорел в бане");
            add("container.heat_and_steam.thermometer", "Термометр");
            add("gui.heat_and_steam.thermometer.temperature", "Температура");
            add("gui.heat_and_steam.thermometer.humidity", "Влажность");
            add("gui.heat_and_steam.thermometer.heat_index", "Ощущается как");
            add("gui.heat_and_steam.thermometer.smoke", "Задымлённость");
            add("gui.heat_and_steam.thermometer.degrees", "%s °C");
            add("gui.heat_and_steam.thermometer.percent", "%s%%");
            add("gui.heat_and_steam.thermometer.sealed", "Парная замкнута");
            add("gui.heat_and_steam.thermometer.leaking", "Парная не замкнута");
            add("gui.heat_and_steam.thermometer.room", "Объём %s, стены %s");
            add("message.heat_and_steam.thermometer.no_stove", "Печь не найдена");
            add("message.heat_and_steam.thermometer.outside", "Термометр не в парной");
            add("message.heat_and_steam.overheat", "Голова кружится, пора выйти");
            add("message.heat_and_steam.steam.heavy", "Тяжёлый пар, камни ещё не раскалились");
            add("entity.heat_and_steam.seat", "Сиденье");
            add("subtitles.heat_and_steam.steam_hiss", "Вода шипит на камнях");
            add("subtitles.heat_and_steam.stone_crack", "Камень трескается");
            add("subtitles.heat_and_steam.stove_crackle", "Печь потрескивает");
            add("subtitles.heat_and_steam.damper_open", "Заслонка открывается");
            add("subtitles.heat_and_steam.damper_close", "Заслонка закрывается");
            add("subtitles.heat_and_steam.whisk_swish", "Свист веника");
            add("subtitles.heat_and_steam.whisk_soak", "Веник запаривается");
            add("subtitles.heat_and_steam.tub_fill", "Ушат наполняется");
            add("subtitles.heat_and_steam.ladle_fill", "Ковш зачерпывает");
            add("subtitles.heat_and_steam.stone_scald", "Камень обжигает");
            add("subtitles.heat_and_steam.stone_quench", "Камень остывает в воде");
            add("subtitles.heat_and_steam.hardening", "Обжигающий холод");
            add("subtitles.heat_and_steam.felt_hat_equip", "Шапка надета");
            add("subtitles.heat_and_steam.chop", "Полено раскалывается");
            add("subtitles.heat_and_steam.wood_load", "Дрова укладываются");
            add("advancements.heat_and_steam.root.title", "Первый пар");
            add("advancements.heat_and_steam.root.description", "Протопить баню и прогреться в ней");
            add("advancements.heat_and_steam.light_steam.title", "С лёгким паром!");
            add("advancements.heat_and_steam.light_steam.description", "Попариться веником, как положено");
            add("advancements.heat_and_steam.smoke_sauna.title", "Баня по-чёрному");
            add("advancements.heat_and_steam.smoke_sauna.description",
                    "Париться там, где копоть на стенах делает пар мягче");
            add("advancements.heat_and_steam.walrus.title", "Морж");
            add("advancements.heat_and_steam.walrus.description", "Три захода из парной в холодную воду подряд");
            add("advancements.heat_and_steam.choked.title", "Угорел…");
            add("advancements.heat_and_steam.choked.description", "Остаться в дыму до потери сознания");
        } else {
            add("itemGroup.heat_and_steam", "Heat & Steam");
            add(ModBlocks.STOVE.get(), "Sauna Stove");
            add(ModBlocks.THERMOMETER.get(), "Thermometer");
            add(ModItems.FELT_HAT.get(), "Felt Sauna Hat");
            add(ModItems.LADLE.get(), "Sauna Ladle");
            add(ModBlocks.TUB.get(), "Water Tub");
            add(ModBlocks.SAUNA_BENCH.get(), "Sauna Bench");
            add(ModBlocks.SAUNA_DOOR.get(), "Sauna Door");
            add(ModBlocks.TALCOCHLORITE_ORE.get(), "Talcochlorite Ore");
            add(ModBlocks.SOOTY_PLANKS.get(), "Sooty Planks");
            add(ModBlocks.SOOTY_LOG.get(), "Sooty Log");
            add(ModBlocks.STOVE_CASING.get(), "Stove Casing");
            add(ModBlocks.CHIMNEY.get(), "Chimney");
            add(ModBlocks.DAMPER.get(), "Damper");
            add(ModItems.RIVER_STONE.get(), "River Stone");
            add(ModItems.ANDESITE_STONE.get(), "Andesite Stone");
            add(ModItems.BASALT_STONE.get(), "Basalt Stone");
            add(ModItems.TALCOCHLORITE_STONE.get(), "Talcochlorite Stone");
            add("message.heat_and_steam.stone.cracked", "A stone cracked");
            add("message.heat_and_steam.stone.too_hot", "The stone is scalding and you cannot hold it");
            add("gui.heat_and_steam.stove.fire", "Fire %s °C");
            add("gui.heat_and_steam.stove.stones", "Stones %s °C");
            add("tooltip.heat_and_steam.stone_heat.warm", "Warm (%s °C)");
            add("tooltip.heat_and_steam.stone_heat.hot", "Hot (%s °C)");
            add("tooltip.heat_and_steam.stone_heat.very_hot", "Very hot (%s °C)");
            add("tooltip.heat_and_steam.stone_heat.faint_red", "Faint red (%s °C)");
            add("tooltip.heat_and_steam.stone_heat.red", "Glowing red (%s °C)");
            add(ModBlocks.CHOPPING_BLOCK.get(), "Chopping Block");
            add(ModBlocks.DRYING_RACK.get(), "Drying Rack");
            add(ModItems.FIREWOOD_BIRCH.get(), "Birch Firewood");
            add(ModItems.FIREWOOD_OAK.get(), "Oak Firewood");
            add(ModItems.FIREWOOD_SPRUCE.get(), "Spruce Firewood");
            add("item.heat_and_steam.firewood_birch.wet", "Damp Birch Firewood");
            add("item.heat_and_steam.firewood_birch.dry", "Dry Birch Firewood");
            add("item.heat_and_steam.firewood_oak.wet", "Damp Oak Firewood");
            add("item.heat_and_steam.firewood_oak.dry", "Dry Oak Firewood");
            add("item.heat_and_steam.firewood_spruce.wet", "Damp Spruce Firewood");
            add("item.heat_and_steam.firewood_spruce.dry", "Dry Spruce Firewood");
            add("message.heat_and_steam.faint", "Everything goes dark…");
            add(ModItems.WHISK_BIRCH.get(), "Birch Sauna Whisk");
            add(ModItems.WHISK_OAK.get(), "Oak Sauna Whisk");
            add("item.heat_and_steam.whisk_birch.soaked", "Soaked Birch Sauna Whisk");
            add("item.heat_and_steam.whisk_oak.soaked", "Soaked Oak Sauna Whisk");
            add("message.heat_and_steam.tub.cold", "The tub water is still cold. Heat the sauna first");
            add("message.heat_and_steam.whisk.dry", "A dry whisk just crumbles. Soak it in a tub");
            add("message.heat_and_steam.whisk.too_cold", "You can only whisk in a hot steam room");
            add("message.heat_and_steam.whisk.received", "%s is whisking you");
            add("message.heat_and_steam.whisk.dried_out", "The whisk has dried out. Soak it again");
            add("effect.heat_and_steam.hardening", "Hardening");
            add("message.heat_and_steam.hardening", "Hardening!");
            add("container.heat_and_steam.stove.t1", "Sauna Stove");
            add("container.heat_and_steam.stove.t2", "Brick Stove");
            add("container.heat_and_steam.stove.t3", "Massive Stove");
            add("effect.heat_and_steam.smoke_poisoning", "Smoke Poisoning");
            add("death.attack.heat_and_steam.smoke_poisoning", "%1$s suffocated in the sauna's smoke");
            add("container.heat_and_steam.thermometer", "Thermometer");
            add("gui.heat_and_steam.thermometer.temperature", "Temperature");
            add("gui.heat_and_steam.thermometer.humidity", "Humidity");
            add("gui.heat_and_steam.thermometer.heat_index", "Feels like");
            add("gui.heat_and_steam.thermometer.smoke", "Smoke");
            add("gui.heat_and_steam.thermometer.degrees", "%s °C");
            add("gui.heat_and_steam.thermometer.percent", "%s%%");
            add("gui.heat_and_steam.thermometer.sealed", "Room is sealed");
            add("gui.heat_and_steam.thermometer.leaking", "Room is not sealed");
            add("gui.heat_and_steam.thermometer.room", "Volume %s, walls %s");
            add("message.heat_and_steam.thermometer.no_stove", "No stove nearby");
            add("message.heat_and_steam.thermometer.outside", "This gauge is not in the steam room");
            add("message.heat_and_steam.overheat", "Your head is swimming, time to step out");
            add("message.heat_and_steam.steam.heavy", "Heavy steam, the stones are not hot enough yet");
            add("entity.heat_and_steam.seat", "Seat");
            add("subtitles.heat_and_steam.steam_hiss", "Water hisses on stones");
            add("subtitles.heat_and_steam.stone_crack", "Stone cracks");
            add("subtitles.heat_and_steam.stove_crackle", "Stove crackles");
            add("subtitles.heat_and_steam.damper_open", "Damper opens");
            add("subtitles.heat_and_steam.damper_close", "Damper closes");
            add("subtitles.heat_and_steam.whisk_swish", "Whisk swishes");
            add("subtitles.heat_and_steam.whisk_soak", "Whisk soaks");
            add("subtitles.heat_and_steam.tub_fill", "Tub fills");
            add("subtitles.heat_and_steam.ladle_fill", "Ladle scoops");
            add("subtitles.heat_and_steam.stone_scald", "Stone scalds");
            add("subtitles.heat_and_steam.stone_quench", "Stone quenches");
            add("subtitles.heat_and_steam.hardening", "Biting cold");
            add("subtitles.heat_and_steam.felt_hat_equip", "Hat put on");
            add("subtitles.heat_and_steam.chop", "Log splits");
            add("subtitles.heat_and_steam.wood_load", "Firewood stacked");
            add("advancements.heat_and_steam.root.title", "First Steam");
            add("advancements.heat_and_steam.root.description", "Fire the sauna up and warm through in it");
            add("advancements.heat_and_steam.light_steam.title", "Enjoy Your Steam!");
            add("advancements.heat_and_steam.light_steam.description", "Take a proper round with the whisk");
            add("advancements.heat_and_steam.smoke_sauna.title", "Smoke Sauna");
            add("advancements.heat_and_steam.smoke_sauna.description",
                    "Steam where the soot on the walls makes the steam softer");
            add("advancements.heat_and_steam.walrus.title", "Polar Bear");
            add("advancements.heat_and_steam.walrus.description", "Three runs from the heat into cold water");
            add("advancements.heat_and_steam.choked.title", "Overcome by Fumes");
            add("advancements.heat_and_steam.choked.description", "Stay in the smoke until you pass out");
        }
    }
}
